server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ms-config
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/config_db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:database/init.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://dummy-issuer}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    duoc.cn1.ms_config: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
